// Mocks generated by Mockito 5.4.6 from annotations
// in task_flow/test/state/notification_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_flow/core/models/notification.dart' as _i4;
import 'package:task_flow/core/services/notification_service.dart' as _i2;
import 'package:task_flow/core/services/preference_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i2.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Notification?> createNotification(
    _i4.Notification? notification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNotification, [notification]),
            returnValue: _i3.Future<_i4.Notification?>.value(),
          )
          as _i3.Future<_i4.Notification?>);

  @override
  _i3.Future<_i4.Notification?> createNotificationForTeam(
    _i4.Notification? notification,
    String? teamId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNotificationForTeam, [
              notification,
              teamId,
            ]),
            returnValue: _i3.Future<_i4.Notification?>.value(),
          )
          as _i3.Future<_i4.Notification?>);

  @override
  _i3.Future<_i4.Notification?> getNotificationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationById, [id]),
            returnValue: _i3.Future<_i4.Notification?>.value(),
          )
          as _i3.Future<_i4.Notification?>);

  @override
  _i3.Future<List<_i4.Notification>> getAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotifications, []),
            returnValue: _i3.Future<List<_i4.Notification>>.value(
              <_i4.Notification>[],
            ),
          )
          as _i3.Future<List<_i4.Notification>>);

  @override
  _i3.Future<bool> updateNotification(_i4.Notification? notification) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotification, [notification]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteNotification(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Notification>> getUnreadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotifications, []),
            returnValue: _i3.Future<List<_i4.Notification>>.value(
              <_i4.Notification>[],
            ),
          )
          as _i3.Future<List<_i4.Notification>>);

  @override
  _i3.Future<List<_i4.Notification>> getNotificationsByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsByType, [type]),
            returnValue: _i3.Future<List<_i4.Notification>>.value(
              <_i4.Notification>[],
            ),
          )
          as _i3.Future<List<_i4.Notification>>);

  @override
  _i3.Future<List<_i4.Notification>> getUnreadNotificationsByType(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationsByType, [type]),
            returnValue: _i3.Future<List<_i4.Notification>>.value(
              <_i4.Notification>[],
            ),
          )
          as _i3.Future<List<_i4.Notification>>);

  @override
  _i3.Future<bool> markAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i4.Notification?> createTaskAssignedNotification({
    required String? taskTitle,
    required String? taskId,
    required String? actorUsername,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskAssignedNotification, [], {
              #taskTitle: taskTitle,
              #taskId: taskId,
              #actorUsername: actorUsername,
            }),
            returnValue: _i3.Future<_i4.Notification?>.value(),
          )
          as _i3.Future<_i4.Notification?>);

  @override
  _i3.Future<_i4.Notification?> createTeamInviteNotification({
    required String? teamName,
    required String? teamId,
    required String? actorUsername,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTeamInviteNotification, [], {
              #teamName: teamName,
              #teamId: teamId,
              #actorUsername: actorUsername,
            }),
            returnValue: _i3.Future<_i4.Notification?>.value(),
          )
          as _i3.Future<_i4.Notification?>);

  @override
  _i3.Future<_i4.Notification?> createTaskCompletedNotification({
    required String? taskTitle,
    required String? taskId,
    required String? actorUsername,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskCompletedNotification, [], {
              #taskTitle: taskTitle,
              #taskId: taskId,
              #actorUsername: actorUsername,
            }),
            returnValue: _i3.Future<_i4.Notification?>.value(),
          )
          as _i3.Future<_i4.Notification?>);
}

/// A class which mocks [PreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferenceService extends _i1.Mock implements _i5.PreferenceService {
  MockPreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
