// Mocks generated by Mockito 5.4.6 from annotations
// in task_flow/test/state/task_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_flow/core/models/task.dart' as _i4;
import 'package:task_flow/core/services/task_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i2.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Task?> createTask(_i4.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<_i4.Task?>.value(),
          )
          as _i3.Future<_i4.Task?>);

  @override
  _i3.Future<_i4.Task?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i3.Future<_i4.Task?>.value(),
          )
          as _i3.Future<_i4.Task?>);

  @override
  _i3.Future<List<_i4.Task>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<bool> updateTask(_i4.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Task>> getTasksByStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [status]),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<List<_i4.Task>> getTasksByPriority(String? priority) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByPriority, [priority]),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<List<_i4.Task>> getMyTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyTasks, [userId]),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<List<_i4.Task>> getTasksByTeam(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByTeam, [teamId]),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<bool> deleteTasksByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTasksByIds, [ids]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateTaskStatus(String? id, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [id, status]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> markAsCompleted(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsCompleted, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> markAsPending(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsPending, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Task>> getOverdueTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, []),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<List<_i4.Task>> getTasksDueToday() =>
      (super.noSuchMethod(
            Invocation.method(#getTasksDueToday, []),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<List<_i4.Task>> getUpcomingTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, []),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
          )
          as _i3.Future<List<_i4.Task>>);
}
