// Mocks generated by Mockito 5.4.6 from annotations
// in task_flow/test/state/team_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_flow/core/models/task_status.dart' as _i5;
import 'package:task_flow/core/models/team.dart' as _i4;
import 'package:task_flow/core/services/team_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TeamService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamService extends _i1.Mock implements _i2.TeamService {
  MockTeamService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Team?> createTeam(_i4.Team? team) =>
      (super.noSuchMethod(
            Invocation.method(#createTeam, [team]),
            returnValue: _i3.Future<_i4.Team?>.value(),
          )
          as _i3.Future<_i4.Team?>);

  @override
  _i3.Future<_i4.Team?> getTeamById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamById, [id]),
            returnValue: _i3.Future<_i4.Team?>.value(),
          )
          as _i3.Future<_i4.Team?>);

  @override
  _i3.Future<List<_i4.Team>> getAllTeams() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTeams, []),
            returnValue: _i3.Future<List<_i4.Team>>.value(<_i4.Team>[]),
          )
          as _i3.Future<List<_i4.Team>>);

  @override
  _i3.Future<bool> updateTeam(_i4.Team? team) =>
      (super.noSuchMethod(
            Invocation.method(#updateTeam, [team]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteTeam(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTeam, [id]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Team>> getTeamsByMember(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamsByMember, [userId]),
            returnValue: _i3.Future<List<_i4.Team>>.value(<_i4.Team>[]),
          )
          as _i3.Future<List<_i4.Team>>);

  @override
  _i3.Future<bool> addMemberToTeam(String? teamId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addMemberToTeam, [teamId, userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeMemberFromTeam(String? teamId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMemberFromTeam, [teamId, userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> addTaskToTeam(String? teamId, String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskToTeam, [teamId, taskId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeTaskFromTeam(String? teamId, String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTaskFromTeam, [teamId, taskId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> addTaskStatus(String? teamId, _i5.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskStatus, [teamId, status]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateTaskStatus(
    String? teamId,
    String? statusId,
    _i5.TaskStatus? updatedStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [
              teamId,
              statusId,
              updatedStatus,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteTaskStatus(String? teamId, String? statusId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskStatus, [teamId, statusId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> reorderTaskStatuses(
    String? teamId,
    List<_i5.TaskStatus>? reorderedStatuses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTaskStatuses, [
              teamId,
              reorderedStatuses,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateSyncStatus(String? teamId, bool? isSynced) =>
      (super.noSuchMethod(
            Invocation.method(#updateSyncStatus, [teamId, isSynced]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteAllTeams() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTeams, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
