// Mocks generated by Mockito 5.4.6 from annotations
// in task_flow/test/state/user_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_flow/core/models/user.dart' as _i4;
import 'package:task_flow/core/services/user_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> signUpUser({
    required String? name,
    required String? email,
    required String? username,
    required String? phoneNumber,
    required String? password,
    _i5.BuildContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpUser, [], {
              #name: name,
              #email: email,
              #username: username,
              #phoneNumber: phoneNumber,
              #password: password,
              #context: context,
            }),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<_i4.User?> login(
    String? username,
    String? password, {
    _i5.BuildContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [username, password],
              {#context: context},
            ),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> syncAvailableUsersInformations({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#syncAvailableUsersInformations, [], {
              #page: page,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> setCurrentUser(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> changeCurrentUserPassword(
    String? newPassword, {
    _i5.BuildContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #changeCurrentUserPassword,
              [newPassword],
              {#context: context},
            ),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestForgetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestForgetPassword, [email]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.User>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i3.Future<List<_i4.User>>.value(<_i4.User>[]),
          )
          as _i3.Future<List<_i4.User>>);
}
