import 'package:path_provider/path_provider.dart';
import 'package:task_flow/core/entities/user_entity.dart';
import 'package:task_flow/objectbox.g.dart';

// NOTE: `objectbox.g.dart` is generated by ObjectBox codegen.
// Run: `flutter pub run build_runner build` or `dart run objectbox_generator` depending on setup.

class DBService {
  DBService._();
  static final DBService _instance = DBService._();
  factory DBService() => _instance;

  Store? _store;
  Box<UserEntity>? _userBox;

  bool _opened = false;
  bool get isAvailable => _opened;

  Future<void> init() async {
    if (_opened) return;
    
    try {
      final dir = await getApplicationDocumentsDirectory();
      _store = openStore(directory: dir.path);
      _userBox = Box<UserEntity>(_store!);
      _opened = true;
    } catch (e) {
      print('Failed to initialize ObjectBox: $e');
      _opened = false;
      _store = null;
      _userBox = null;
      rethrow;
    }
  }

  Box<UserEntity>? get userBox {
    if (!_opened || _userBox == null) {
      return null;
    }
    return _userBox;
  }

  Store? get store {
    if (!_opened) {
      return null;
    }
    return _store;
  }

  void close() {
    if (_opened && _store != null) {
      _store!.close();
      _opened = false;
    }
  }
}
