import 'package:path_provider/path_provider.dart';
import 'package:task_manager/core/entities/user_entity.dart';
import 'package:task_manager/objectbox.g.dart';

// NOTE: `objectbox.g.dart` is generated by ObjectBox codegen.
// Run: `flutter pub run build_runner build` or `dart run objectbox_generator` depending on setup.

class DBService {
  DBService._();
  static final DBService _instance = DBService._();
  factory DBService() => _instance;

  late final Store _store;
  Box<UserEntity>? _userBox;

  bool _opened = false;

  Future<void> init() async {
    if (_opened) return;
    final dir = await getApplicationDocumentsDirectory();
    _store = openStore(directory: dir.path);
    _userBox = Box<UserEntity>(_store);
    _opened = true;
  }

  Box<UserEntity> get userBox {
    if (!_opened || _userBox == null) {
      throw StateError(
        'DBService not initialized. Call DBService().init() first.',
      );
    }
    return _userBox!;
  }

  Store get store {
    if (!_opened) {
      throw StateError(
        'DBService not initialized. Call DBService().init() first.',
      );
    }
    return _store;
  }

  void close() {
    if (_opened) {
      _store.close();
      _opened = false;
    }
  }
}
