import 'package:flutter/cupertino.dart';
import 'package:path_provider/path_provider.dart';
import 'package:task_flow/core/entities/user_entity.dart';
import 'package:task_flow/core/entities/task_entity.dart';
import 'package:task_flow/core/entities/team_entity.dart';
import 'package:task_flow/core/entities/notification_entity.dart';
import 'package:task_flow/objectbox.g.dart';

// NOTE: `objectbox.g.dart` is generated by ObjectBox codegen.
// Run: `flutter pub run build_runner build` or `dart run objectbox_generator` depending on setup.

class DBService {
  DBService._();
  static final DBService _instance = DBService._();
  factory DBService() => _instance;

  Store? _store;
  Box<UserEntity>? _userBox;
  Box<TaskEntity>? _taskBox;
  Box<TeamEntity>? _teamBox;
  Box<NotificationEntity>? _notificationBox;

  bool _opened = false;
  bool get isAvailable => _opened;

  Future<void> init() async {
    if (_opened) return;

    try {
      final dir = await getApplicationDocumentsDirectory();
      _store = await openStore(directory: dir.path);
      _userBox = Box<UserEntity>(_store!);
      _taskBox = Box<TaskEntity>(_store!);
      _teamBox = Box<TeamEntity>(_store!);
      _notificationBox = Box<NotificationEntity>(_store!);
      _opened = true;
    } catch (e) {
      debugPrint('Failed to initialize ObjectBox: $e');
      _opened = false;
      _store = null;
      _userBox = null;
      _taskBox = null;
      _teamBox = null;
      _notificationBox = null;
      rethrow;
    }
  }

  Box<UserEntity>? get userBox {
    if (!_opened || _userBox == null) {
      return null;
    }
    return _userBox;
  }

  Box<TaskEntity>? get taskBox {
    if (!_opened || _taskBox == null) {
      return null;
    }
    return _taskBox;
  }

  Box<TeamEntity>? get teamBox {
    if (!_opened || _teamBox == null) {
      return null;
    }
    return _teamBox;
  }

  Box<NotificationEntity>? get notificationBox {
    if (!_opened || _notificationBox == null) {
      return null;
    }
    return _notificationBox;
  }

  Store? get store {
    if (!_opened) {
      return null;
    }
    return _store;
  }

  void close() {
    if (_opened && _store != null) {
      _store!.close();
      _opened = false;
    }
  }
}
