// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';

import 'core/models/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 772303950422415881),
      name: 'UserEntity',
      lastPropertyId: const IdUid(12, 135041333198133376),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1525211519435609053),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7051138316127784068),
            name: 'apiUserId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6404071738839563443),
            name: 'username',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2402715980082797518),
            name: 'fullName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1989123902742884831),
            name: 'password',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8025562844652251580),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1483887975921106131),
            name: 'phoneNumber',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 836196098256066830),
            name: 'userGroupsJson',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4360288102706087886),
            name: 'userOrgUnitIdsJson',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 9082837829193722667),
            name: 'isLogin',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 2112599267384852441),
            name: 'createdAt',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 135041333198133376),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Store openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) =>
    Store(getObjectBoxModel(),
        directory: directory,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 772303950422415881),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    UserEntity: EntityDefinition<UserEntity>(
        model: _entities[0],
        toOneRelations: (UserEntity object) => [],
        toManyRelations: (UserEntity object) => {},
        getId: (UserEntity object) => object.id,
        setId: (UserEntity object, int id) {
          object.id = id;
        },
        objectToFB: (UserEntity object, fb.Builder fbb) {
          final apiUserIdOffset = fbb.writeString(object.apiUserId);
          final usernameOffset = fbb.writeString(object.username);
          final fullNameOffset = object.fullName == null
              ? null
              : fbb.writeString(object.fullName!);
          final passwordOffset = object.password == null
              ? null
              : fbb.writeString(object.password!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final phoneNumberOffset = object.phoneNumber == null
              ? null
              : fbb.writeString(object.phoneNumber!);
          final userGroupsJsonOffset = object.userGroupsJson == null
              ? null
              : fbb.writeString(object.userGroupsJson!);
          final userOrgUnitIdsJsonOffset = object.userOrgUnitIdsJson == null
              ? null
              : fbb.writeString(object.userOrgUnitIdsJson!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, apiUserIdOffset);
          fbb.addOffset(2, usernameOffset);
          fbb.addOffset(3, fullNameOffset);
          fbb.addOffset(4, passwordOffset);
          fbb.addOffset(5, emailOffset);
          fbb.addOffset(6, phoneNumberOffset);
          fbb.addOffset(7, userGroupsJsonOffset);
          fbb.addOffset(8, userOrgUnitIdsJsonOffset);
          fbb.addBool(9, object.isLogin);
          fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = UserEntity(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              apiUserId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              username: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              fullName: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              password: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              phoneNumber: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              userGroupsJson: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              userOrgUnitIdsJson: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 20),
              isLogin: const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false),
              createdAt: DateTime.fromMillisecondsSinceEpoch(const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)),
              updatedAt: DateTime.fromMillisecondsSinceEpoch(const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0)));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// see [UserEntity.id]
  static final id =
      QueryIntegerProperty<UserEntity>(_entities[0].properties[0]);

  /// see [UserEntity.apiUserId]
  static final apiUserId =
      QueryStringProperty<UserEntity>(_entities[0].properties[1]);

  /// see [UserEntity.username]
  static final username =
      QueryStringProperty<UserEntity>(_entities[0].properties[2]);

  /// see [UserEntity.fullName]
  static final fullName =
      QueryStringProperty<UserEntity>(_entities[0].properties[3]);

  /// see [UserEntity.password]
  static final password =
      QueryStringProperty<UserEntity>(_entities[0].properties[4]);

  /// see [UserEntity.email]
  static final email =
      QueryStringProperty<UserEntity>(_entities[0].properties[5]);

  /// see [UserEntity.phoneNumber]
  static final phoneNumber =
      QueryStringProperty<UserEntity>(_entities[0].properties[6]);

  /// see [UserEntity.userGroupsJson]
  static final userGroupsJson =
      QueryStringProperty<UserEntity>(_entities[0].properties[7]);

  /// see [UserEntity.userOrgUnitIdsJson]
  static final userOrgUnitIdsJson =
      QueryStringProperty<UserEntity>(_entities[0].properties[8]);

  /// see [UserEntity.isLogin]
  static final isLogin =
      QueryBooleanProperty<UserEntity>(_entities[0].properties[9]);

  /// see [UserEntity.createdAt]
  static final createdAt =
      QueryIntegerProperty<UserEntity>(_entities[0].properties[10]);

  /// see [UserEntity.updatedAt]
  static final updatedAt =
      QueryIntegerProperty<UserEntity>(_entities[0].properties[11]);
}
