// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/entities/notification_entity.dart';
import 'core/entities/task_entity.dart';
import 'core/entities/team_entity.dart';
import 'core/entities/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 772303950422415881),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(12, 135041333198133376),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1525211519435609053),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7051138316127784068),
        name: 'apiUserId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6404071738839563443),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2402715980082797518),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1989123902742884831),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8025562844652251580),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1483887975921106131),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9082837829193722667),
        name: 'isLogin',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2112599267384852441),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 135041333198133376),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 614660561691660408),
    name: 'NotificationEntity',
    lastPropertyId: const obx_int.IdUid(14, 3863776433235736798),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8254734781835588472),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 147813581869063538),
        name: 'notificationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 2229165379850530037),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6531379092925573587),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6321885893034312839),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3683634050326075010),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 199258760478824042),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5900849718058338),
        name: 'relatedEntityId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6243593963600987893),
        name: 'relatedEntityType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 243286664669834715),
        name: 'actorUserId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8244282929213007453),
        name: 'actorUsername',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1901217508343952063),
        name: 'actorAvatarUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6107301804069805780),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1049038385883546181),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3863776433235736798),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 636520496469286108),
    name: 'TaskEntity',
    lastPropertyId: const obx_int.IdUid(24, 3590199673161262875),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3960293065232813672),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 796404430768788961),
        name: 'taskId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 2455266859196832607),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7942440886971976073),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6980630822084538123),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2735632824927333940),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4447753324190728148),
        name: 'priority',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 103390021624249662),
        name: 'assignedToUserId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1980092744313681671),
        name: 'assignedToUsername',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4694781489134782213),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4816753784983392056),
        name: 'completedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8697813631308840942),
        name: 'projectId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1540955089240229173),
        name: 'projectName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8269989544298135620),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7435249371995302165),
        name: 'attachmentsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3790149430168849655),
        name: 'progress',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7478973536312850089),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 7859719176504303709),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7617994320264726487),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 1563129029436451486),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6796764885512761521),
        name: 'assignedUserIdsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 1124996016942223540),
        name: 'teamId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 4025574684188529509),
        name: 'teamName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8943130831190389910),
        name: 'subtasksJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 3590199673161262875),
        name: 'remindMe',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8634427917478567143),
    name: 'TeamEntity',
    lastPropertyId: const obx_int.IdUid(16, 1984349909510261685),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4755454378011354988),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6046622711719698281),
        name: 'teamId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 940942428753482839),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5172081056315198200),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 1715280144268285282),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9069387595676232939),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7534465306864814411),
        name: 'avatarUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8317316129997791116),
        name: 'memberCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8780119160444460291),
        name: 'createdByUserId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3972177163213076799),
        name: 'createdByUsername',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2025820226576621978),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5115795330784668216),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7948209602236517186),
        name: 'isSynced',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(5, 811543964467735373),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6555534071892076546),
        name: 'memberIdsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6498061324321972108),
        name: 'taskIdsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6839939419456406559),
        name: 'customTaskStatusesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7023405807681367260),
        name: 'teamIcon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1984349909510261685),
        name: 'teamColor',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8634427917478567143),
    lastIndexId: const obx_int.IdUid(5, 811543964467735373),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [836196098256066830, 4360288102706087886],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[0],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.id,
      setId: (UserEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final apiUserIdOffset = fbb.writeString(object.apiUserId);
        final usernameOffset = fbb.writeString(object.username);
        final fullNameOffset = object.fullName == null
            ? null
            : fbb.writeString(object.fullName!);
        final passwordOffset = object.password == null
            ? null
            : fbb.writeString(object.password!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, apiUserIdOffset);
        fbb.addOffset(2, usernameOffset);
        fbb.addOffset(3, fullNameOffset);
        fbb.addOffset(4, passwordOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addOffset(6, phoneNumberOffset);
        fbb.addBool(9, object.isLogin);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiUserIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isLoginParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final object = UserEntity(
          id: idParam,
          apiUserId: apiUserIdParam,
          username: usernameParam,
          fullName: fullNameParam,
          password: passwordParam,
          email: emailParam,
          phoneNumber: phoneNumberParam,
          isLogin: isLoginParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    NotificationEntity: obx_int.EntityDefinition<NotificationEntity>(
      model: _entities[1],
      toOneRelations: (NotificationEntity object) => [],
      toManyRelations: (NotificationEntity object) => {},
      getId: (NotificationEntity object) => object.id,
      setId: (NotificationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NotificationEntity object, fb.Builder fbb) {
        final notificationIdOffset = fbb.writeString(object.notificationId);
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = object.body == null
            ? null
            : fbb.writeString(object.body!);
        final typeOffset = fbb.writeString(object.type);
        final relatedEntityIdOffset = object.relatedEntityId == null
            ? null
            : fbb.writeString(object.relatedEntityId!);
        final relatedEntityTypeOffset = object.relatedEntityType == null
            ? null
            : fbb.writeString(object.relatedEntityType!);
        final actorUserIdOffset = object.actorUserId == null
            ? null
            : fbb.writeString(object.actorUserId!);
        final actorUsernameOffset = object.actorUsername == null
            ? null
            : fbb.writeString(object.actorUsername!);
        final actorAvatarUrlOffset = object.actorAvatarUrl == null
            ? null
            : fbb.writeString(object.actorAvatarUrl!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, notificationIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, bodyOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addBool(5, object.isRead);
        fbb.addOffset(6, relatedEntityIdOffset);
        fbb.addOffset(7, relatedEntityTypeOffset);
        fbb.addOffset(8, actorUserIdOffset);
        fbb.addOffset(9, actorUsernameOffset);
        fbb.addOffset(10, actorAvatarUrlOffset);
        fbb.addInt64(11, object.createdAt.millisecondsSinceEpoch);
        fbb.addBool(12, object.isSynced);
        fbb.addOffset(13, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final notificationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final relatedEntityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final relatedEntityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final actorUserIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final actorUsernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final actorAvatarUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final object = NotificationEntity(
          id: idParam,
          notificationId: notificationIdParam,
          title: titleParam,
          body: bodyParam,
          type: typeParam,
          isRead: isReadParam,
          relatedEntityId: relatedEntityIdParam,
          relatedEntityType: relatedEntityTypeParam,
          actorUserId: actorUserIdParam,
          actorUsername: actorUsernameParam,
          actorAvatarUrl: actorAvatarUrlParam,
          createdAt: createdAtParam,
          isSynced: isSyncedParam,
          metadataJson: metadataJsonParam,
        );

        return object;
      },
    ),
    TaskEntity: obx_int.EntityDefinition<TaskEntity>(
      model: _entities[2],
      toOneRelations: (TaskEntity object) => [],
      toManyRelations: (TaskEntity object) => {},
      getId: (TaskEntity object) => object.id,
      setId: (TaskEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TaskEntity object, fb.Builder fbb) {
        final taskIdOffset = fbb.writeString(object.taskId);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final statusOffset = fbb.writeString(object.status);
        final priorityOffset = fbb.writeString(object.priority);
        final assignedToUserIdOffset = object.assignedToUserId == null
            ? null
            : fbb.writeString(object.assignedToUserId!);
        final assignedToUsernameOffset = object.assignedToUsername == null
            ? null
            : fbb.writeString(object.assignedToUsername!);
        final projectIdOffset = object.projectId == null
            ? null
            : fbb.writeString(object.projectId!);
        final projectNameOffset = object.projectName == null
            ? null
            : fbb.writeString(object.projectName!);
        final tagsJsonOffset = object.tagsJson == null
            ? null
            : fbb.writeString(object.tagsJson!);
        final attachmentsJsonOffset = object.attachmentsJson == null
            ? null
            : fbb.writeString(object.attachmentsJson!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final assignedUserIdsJsonOffset = object.assignedUserIdsJson == null
            ? null
            : fbb.writeString(object.assignedUserIdsJson!);
        final teamIdOffset = object.teamId == null
            ? null
            : fbb.writeString(object.teamId!);
        final teamNameOffset = object.teamName == null
            ? null
            : fbb.writeString(object.teamName!);
        final subtasksJsonOffset = object.subtasksJson == null
            ? null
            : fbb.writeString(object.subtasksJson!);
        fbb.startTable(25);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, taskIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, statusOffset);
        fbb.addOffset(5, priorityOffset);
        fbb.addOffset(6, assignedToUserIdOffset);
        fbb.addOffset(7, assignedToUsernameOffset);
        fbb.addInt64(8, object.dueDate?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.completedAt?.millisecondsSinceEpoch);
        fbb.addOffset(10, projectIdOffset);
        fbb.addOffset(11, projectNameOffset);
        fbb.addOffset(12, tagsJsonOffset);
        fbb.addOffset(13, attachmentsJsonOffset);
        fbb.addInt64(14, object.progress);
        fbb.addBool(15, object.isSynced);
        fbb.addInt64(16, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(17, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(18, categoryOffset);
        fbb.addOffset(19, assignedUserIdsJsonOffset);
        fbb.addOffset(20, teamIdOffset);
        fbb.addOffset(21, teamNameOffset);
        fbb.addOffset(22, subtasksJsonOffset);
        fbb.addBool(23, object.remindMe);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final completedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final taskIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final priorityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final assignedToUserIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final assignedToUsernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final assignedUserIdsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final teamNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final dueDateParam = dueDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueDateValue);
        final completedAtParam = completedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(completedAtValue);
        final projectIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final projectNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final tagsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final attachmentsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final subtasksJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final remindMeParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          50,
        );
        final progressParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          34,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0),
        );
        final object = TaskEntity(
          id: idParam,
          taskId: taskIdParam,
          title: titleParam,
          description: descriptionParam,
          status: statusParam,
          priority: priorityParam,
          category: categoryParam,
          assignedToUserId: assignedToUserIdParam,
          assignedToUsername: assignedToUsernameParam,
          assignedUserIdsJson: assignedUserIdsJsonParam,
          teamId: teamIdParam,
          teamName: teamNameParam,
          dueDate: dueDateParam,
          completedAt: completedAtParam,
          projectId: projectIdParam,
          projectName: projectNameParam,
          tagsJson: tagsJsonParam,
          attachmentsJson: attachmentsJsonParam,
          subtasksJson: subtasksJsonParam,
          remindMe: remindMeParam,
          progress: progressParam,
          isSynced: isSyncedParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    TeamEntity: obx_int.EntityDefinition<TeamEntity>(
      model: _entities[3],
      toOneRelations: (TeamEntity object) => [],
      toManyRelations: (TeamEntity object) => {},
      getId: (TeamEntity object) => object.id,
      setId: (TeamEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TeamEntity object, fb.Builder fbb) {
        final teamIdOffset = fbb.writeString(object.teamId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final avatarUrlOffset = object.avatarUrl == null
            ? null
            : fbb.writeString(object.avatarUrl!);
        final createdByUserIdOffset = object.createdByUserId == null
            ? null
            : fbb.writeString(object.createdByUserId!);
        final createdByUsernameOffset = object.createdByUsername == null
            ? null
            : fbb.writeString(object.createdByUsername!);
        final memberIdsJsonOffset = object.memberIdsJson == null
            ? null
            : fbb.writeString(object.memberIdsJson!);
        final taskIdsJsonOffset = object.taskIdsJson == null
            ? null
            : fbb.writeString(object.taskIdsJson!);
        final customTaskStatusesJsonOffset =
            object.customTaskStatusesJson == null
            ? null
            : fbb.writeString(object.customTaskStatusesJson!);
        final teamIconOffset = object.teamIcon == null
            ? null
            : fbb.writeString(object.teamIcon!);
        final teamColorOffset = object.teamColor == null
            ? null
            : fbb.writeString(object.teamColor!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, teamIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, avatarUrlOffset);
        fbb.addInt64(5, object.memberCount);
        fbb.addOffset(6, createdByUserIdOffset);
        fbb.addOffset(7, createdByUsernameOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(10, object.isSynced);
        fbb.addOffset(11, memberIdsJsonOffset);
        fbb.addOffset(12, taskIdsJsonOffset);
        fbb.addOffset(13, customTaskStatusesJsonOffset);
        fbb.addOffset(14, teamIconOffset);
        fbb.addOffset(15, teamColorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final teamIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final avatarUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final memberCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final createdByUserIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdByUsernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final memberIdsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final taskIdsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final customTaskStatusesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final teamIconParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final teamColorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = TeamEntity(
          id: idParam,
          teamId: teamIdParam,
          name: nameParam,
          description: descriptionParam,
          avatarUrl: avatarUrlParam,
          memberCount: memberCountParam,
          createdByUserId: createdByUserIdParam,
          createdByUsername: createdByUsernameParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isSynced: isSyncedParam,
          memberIdsJson: memberIdsJsonParam,
          taskIdsJson: taskIdsJsonParam,
          customTaskStatusesJson: customTaskStatusesJsonParam,
          teamIcon: teamIconParam,
          teamColor: teamColorParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.id].
  static final id = obx.QueryIntegerProperty<UserEntity>(
    _entities[0].properties[0],
  );

  /// See [UserEntity.apiUserId].
  static final apiUserId = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[1],
  );

  /// See [UserEntity.username].
  static final username = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[2],
  );

  /// See [UserEntity.fullName].
  static final fullName = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[3],
  );

  /// See [UserEntity.password].
  static final password = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[4],
  );

  /// See [UserEntity.email].
  static final email = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[5],
  );

  /// See [UserEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[6],
  );

  /// See [UserEntity.isLogin].
  static final isLogin = obx.QueryBooleanProperty<UserEntity>(
    _entities[0].properties[7],
  );

  /// See [UserEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<UserEntity>(
    _entities[0].properties[8],
  );

  /// See [UserEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserEntity>(
    _entities[0].properties[9],
  );
}

/// [NotificationEntity] entity fields to define ObjectBox queries.
class NotificationEntity_ {
  /// See [NotificationEntity.id].
  static final id = obx.QueryIntegerProperty<NotificationEntity>(
    _entities[1].properties[0],
  );

  /// See [NotificationEntity.notificationId].
  static final notificationId = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[1],
  );

  /// See [NotificationEntity.title].
  static final title = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[2],
  );

  /// See [NotificationEntity.body].
  static final body = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[3],
  );

  /// See [NotificationEntity.type].
  static final type = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[4],
  );

  /// See [NotificationEntity.isRead].
  static final isRead = obx.QueryBooleanProperty<NotificationEntity>(
    _entities[1].properties[5],
  );

  /// See [NotificationEntity.relatedEntityId].
  static final relatedEntityId = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[6],
  );

  /// See [NotificationEntity.relatedEntityType].
  static final relatedEntityType = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[7],
  );

  /// See [NotificationEntity.actorUserId].
  static final actorUserId = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[8],
  );

  /// See [NotificationEntity.actorUsername].
  static final actorUsername = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[9],
  );

  /// See [NotificationEntity.actorAvatarUrl].
  static final actorAvatarUrl = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[10],
  );

  /// See [NotificationEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<NotificationEntity>(
    _entities[1].properties[11],
  );

  /// See [NotificationEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<NotificationEntity>(
    _entities[1].properties[12],
  );

  /// See [NotificationEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<NotificationEntity>(
    _entities[1].properties[13],
  );
}

/// [TaskEntity] entity fields to define ObjectBox queries.
class TaskEntity_ {
  /// See [TaskEntity.id].
  static final id = obx.QueryIntegerProperty<TaskEntity>(
    _entities[2].properties[0],
  );

  /// See [TaskEntity.taskId].
  static final taskId = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[1],
  );

  /// See [TaskEntity.title].
  static final title = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[2],
  );

  /// See [TaskEntity.description].
  static final description = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[3],
  );

  /// See [TaskEntity.status].
  static final status = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[4],
  );

  /// See [TaskEntity.priority].
  static final priority = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[5],
  );

  /// See [TaskEntity.assignedToUserId].
  static final assignedToUserId = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[6],
  );

  /// See [TaskEntity.assignedToUsername].
  static final assignedToUsername = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[7],
  );

  /// See [TaskEntity.dueDate].
  static final dueDate = obx.QueryDateProperty<TaskEntity>(
    _entities[2].properties[8],
  );

  /// See [TaskEntity.completedAt].
  static final completedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[2].properties[9],
  );

  /// See [TaskEntity.projectId].
  static final projectId = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[10],
  );

  /// See [TaskEntity.projectName].
  static final projectName = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[11],
  );

  /// See [TaskEntity.tagsJson].
  static final tagsJson = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[12],
  );

  /// See [TaskEntity.attachmentsJson].
  static final attachmentsJson = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[13],
  );

  /// See [TaskEntity.progress].
  static final progress = obx.QueryIntegerProperty<TaskEntity>(
    _entities[2].properties[14],
  );

  /// See [TaskEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<TaskEntity>(
    _entities[2].properties[15],
  );

  /// See [TaskEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TaskEntity>(
    _entities[2].properties[16],
  );

  /// See [TaskEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TaskEntity>(
    _entities[2].properties[17],
  );

  /// See [TaskEntity.category].
  static final category = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[18],
  );

  /// See [TaskEntity.assignedUserIdsJson].
  static final assignedUserIdsJson = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[19],
  );

  /// See [TaskEntity.teamId].
  static final teamId = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[20],
  );

  /// See [TaskEntity.teamName].
  static final teamName = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[21],
  );

  /// See [TaskEntity.subtasksJson].
  static final subtasksJson = obx.QueryStringProperty<TaskEntity>(
    _entities[2].properties[22],
  );

  /// See [TaskEntity.remindMe].
  static final remindMe = obx.QueryBooleanProperty<TaskEntity>(
    _entities[2].properties[23],
  );
}

/// [TeamEntity] entity fields to define ObjectBox queries.
class TeamEntity_ {
  /// See [TeamEntity.id].
  static final id = obx.QueryIntegerProperty<TeamEntity>(
    _entities[3].properties[0],
  );

  /// See [TeamEntity.teamId].
  static final teamId = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[1],
  );

  /// See [TeamEntity.name].
  static final name = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[2],
  );

  /// See [TeamEntity.description].
  static final description = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[3],
  );

  /// See [TeamEntity.avatarUrl].
  static final avatarUrl = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[4],
  );

  /// See [TeamEntity.memberCount].
  static final memberCount = obx.QueryIntegerProperty<TeamEntity>(
    _entities[3].properties[5],
  );

  /// See [TeamEntity.createdByUserId].
  static final createdByUserId = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[6],
  );

  /// See [TeamEntity.createdByUsername].
  static final createdByUsername = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[7],
  );

  /// See [TeamEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TeamEntity>(
    _entities[3].properties[8],
  );

  /// See [TeamEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TeamEntity>(
    _entities[3].properties[9],
  );

  /// See [TeamEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<TeamEntity>(
    _entities[3].properties[10],
  );

  /// See [TeamEntity.memberIdsJson].
  static final memberIdsJson = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[11],
  );

  /// See [TeamEntity.taskIdsJson].
  static final taskIdsJson = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[12],
  );

  /// See [TeamEntity.customTaskStatusesJson].
  static final customTaskStatusesJson = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[13],
  );

  /// See [TeamEntity.teamIcon].
  static final teamIcon = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[14],
  );

  /// See [TeamEntity.teamColor].
  static final teamColor = obx.QueryStringProperty<TeamEntity>(
    _entities[3].properties[15],
  );
}
