// Mocks generated by Mockito 5.4.6 from annotations
// in task_flow/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:package_info_plus/package_info_plus.dart' as _i2;
import 'package:task_flow/core/models/notification.dart' as _i13;
import 'package:task_flow/core/models/task.dart' as _i8;
import 'package:task_flow/core/models/task_status.dart' as _i11;
import 'package:task_flow/core/models/team.dart' as _i10;
import 'package:task_flow/core/models/user.dart' as _i6;
import 'package:task_flow/core/services/notification_service.dart' as _i12;
import 'package:task_flow/core/services/preference_service.dart' as _i14;
import 'package:task_flow/core/services/system_info_service.dart' as _i15;
import 'package:task_flow/core/services/task_service.dart' as _i7;
import 'package:task_flow/core/services/team_service.dart' as _i9;
import 'package:task_flow/core/services/user_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePackageInfo_0 extends _i1.SmartFake implements _i2.PackageInfo {
  _FakePackageInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i3.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiFields =>
      (super.noSuchMethod(
            Invocation.getter(#apiFields),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#apiFields),
            ),
          )
          as String);

  @override
  _i5.Future<_i6.User?> signUpUser({
    required String? username,
    required String? password,
    required String? email,
    required String? firstName,
    required String? surname,
    required String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpUser, [], {
              #username: username,
              #password: password,
              #email: email,
              #firstName: firstName,
              #surname: surname,
              #phoneNumber: phoneNumber,
            }),
            returnValue: _i5.Future<_i6.User?>.value(),
          )
          as _i5.Future<_i6.User?>);

  @override
  _i5.Future<_i6.User?> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i5.Future<_i6.User?>.value(),
          )
          as _i5.Future<_i6.User?>);

  @override
  _i5.Future<void> syncAvailableUsersInformations({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncAvailableUsersInformations, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i6.User?>.value(),
          )
          as _i5.Future<_i6.User?>);

  @override
  _i5.Future<void> setCurrentUser(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> changeCurrentUserPassword(
    String? oldPassword,
    String? newPassword, {
    String? baseUrl = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #changeCurrentUserPassword,
              [oldPassword, newPassword],
              {#baseUrl: baseUrl},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i6.User>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<List<_i6.User>>.value(<_i6.User>[]),
          )
          as _i5.Future<List<_i6.User>>);
}

/// A class which mocks [TaskService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskService extends _i1.Mock implements _i7.TaskService {
  MockTaskService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i8.Task?> createTask(_i8.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i5.Future<_i8.Task?>.value(),
          )
          as _i5.Future<_i8.Task?>);

  @override
  _i5.Future<_i8.Task?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i5.Future<_i8.Task?>.value(),
          )
          as _i5.Future<_i8.Task?>);

  @override
  _i5.Future<List<_i8.Task>> getAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTasks, []),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<bool> updateTask(_i8.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i8.Task>> getTasksByStatus(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [status]),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<List<_i8.Task>> getTasksByPriority(String? priority) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByPriority, [priority]),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<List<_i8.Task>> getMyTasks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyTasks, [userId]),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<List<_i8.Task>> getTasksByTeam(String? teamId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByTeam, [teamId]),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<bool> deleteTasksByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTasksByIds, [ids]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateTaskStatus(String? id, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [id, status]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> markAsCompleted(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsCompleted, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> markAsPending(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsPending, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i8.Task>> getOverdueTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, []),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<List<_i8.Task>> getTasksDueToday() =>
      (super.noSuchMethod(
            Invocation.method(#getTasksDueToday, []),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);

  @override
  _i5.Future<List<_i8.Task>> getUpcomingTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingTasks, []),
            returnValue: _i5.Future<List<_i8.Task>>.value(<_i8.Task>[]),
          )
          as _i5.Future<List<_i8.Task>>);
}

/// A class which mocks [TeamService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamService extends _i1.Mock implements _i9.TeamService {
  MockTeamService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.Team?> createTeam(_i10.Team? team) =>
      (super.noSuchMethod(
            Invocation.method(#createTeam, [team]),
            returnValue: _i5.Future<_i10.Team?>.value(),
          )
          as _i5.Future<_i10.Team?>);

  @override
  _i5.Future<_i10.Team?> getTeamById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamById, [id]),
            returnValue: _i5.Future<_i10.Team?>.value(),
          )
          as _i5.Future<_i10.Team?>);

  @override
  _i5.Future<List<_i10.Team>> getAllTeams() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTeams, []),
            returnValue: _i5.Future<List<_i10.Team>>.value(<_i10.Team>[]),
          )
          as _i5.Future<List<_i10.Team>>);

  @override
  _i5.Future<bool> updateTeam(_i10.Team? team) =>
      (super.noSuchMethod(
            Invocation.method(#updateTeam, [team]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteTeam(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTeam, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i10.Team>> getTeamsByMember(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTeamsByMember, [userId]),
            returnValue: _i5.Future<List<_i10.Team>>.value(<_i10.Team>[]),
          )
          as _i5.Future<List<_i10.Team>>);

  @override
  _i5.Future<bool> addMemberToTeam(String? teamId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addMemberToTeam, [teamId, userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeMemberFromTeam(String? teamId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMemberFromTeam, [teamId, userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> addTaskToTeam(String? teamId, String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskToTeam, [teamId, taskId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeTaskFromTeam(String? teamId, String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTaskFromTeam, [teamId, taskId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> addTaskStatus(String? teamId, _i11.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskStatus, [teamId, status]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateTaskStatus(
    String? teamId,
    String? statusId,
    _i11.TaskStatus? updatedStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [
              teamId,
              statusId,
              updatedStatus,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteTaskStatus(String? teamId, String? statusId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskStatus, [teamId, statusId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> reorderTaskStatuses(
    String? teamId,
    List<_i11.TaskStatus>? reorderedStatuses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTaskStatuses, [
              teamId,
              reorderedStatuses,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateSyncStatus(String? teamId, bool? isSynced) =>
      (super.noSuchMethod(
            Invocation.method(#updateSyncStatus, [teamId, isSynced]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteAllTeams() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTeams, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i12.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i13.Notification?> createNotification(
    _i13.Notification? notification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNotification, [notification]),
            returnValue: _i5.Future<_i13.Notification?>.value(),
          )
          as _i5.Future<_i13.Notification?>);

  @override
  _i5.Future<_i13.Notification?> getNotificationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationById, [id]),
            returnValue: _i5.Future<_i13.Notification?>.value(),
          )
          as _i5.Future<_i13.Notification?>);

  @override
  _i5.Future<List<_i13.Notification>> getAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotifications, []),
            returnValue: _i5.Future<List<_i13.Notification>>.value(
              <_i13.Notification>[],
            ),
          )
          as _i5.Future<List<_i13.Notification>>);

  @override
  _i5.Future<bool> updateNotification(_i13.Notification? notification) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotification, [notification]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteNotification(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i13.Notification>> getUnreadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotifications, []),
            returnValue: _i5.Future<List<_i13.Notification>>.value(
              <_i13.Notification>[],
            ),
          )
          as _i5.Future<List<_i13.Notification>>);

  @override
  _i5.Future<List<_i13.Notification>> getNotificationsByType(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsByType, [type]),
            returnValue: _i5.Future<List<_i13.Notification>>.value(
              <_i13.Notification>[],
            ),
          )
          as _i5.Future<List<_i13.Notification>>);

  @override
  _i5.Future<List<_i13.Notification>> getUnreadNotificationsByType(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationsByType, [type]),
            returnValue: _i5.Future<List<_i13.Notification>>.value(
              <_i13.Notification>[],
            ),
          )
          as _i5.Future<List<_i13.Notification>>);

  @override
  _i5.Future<bool> markAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i13.Notification?> createTaskAssignedNotification({
    required String? taskTitle,
    required String? taskId,
    required String? actorUsername,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskAssignedNotification, [], {
              #taskTitle: taskTitle,
              #taskId: taskId,
              #actorUsername: actorUsername,
            }),
            returnValue: _i5.Future<_i13.Notification?>.value(),
          )
          as _i5.Future<_i13.Notification?>);

  @override
  _i5.Future<_i13.Notification?> createTeamInviteNotification({
    required String? teamName,
    required String? teamId,
    required String? actorUsername,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTeamInviteNotification, [], {
              #teamName: teamName,
              #teamId: teamId,
              #actorUsername: actorUsername,
            }),
            returnValue: _i5.Future<_i13.Notification?>.value(),
          )
          as _i5.Future<_i13.Notification?>);

  @override
  _i5.Future<_i13.Notification?> createTaskCompletedNotification({
    required String? taskTitle,
    required String? taskId,
    required String? actorUsername,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTaskCompletedNotification, [], {
              #taskTitle: taskTitle,
              #taskId: taskId,
              #actorUsername: actorUsername,
            }),
            returnValue: _i5.Future<_i13.Notification?>.value(),
          )
          as _i5.Future<_i13.Notification?>);
}

/// A class which mocks [PreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferenceService extends _i1.Mock implements _i14.PreferenceService {
  MockPreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool?> getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SystemInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemInfoService extends _i1.Mock implements _i15.SystemInfoService {
  MockSystemInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PackageInfo> getPackageInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getPackageInfo, []),
            returnValue: _i5.Future<_i2.PackageInfo>.value(
              _FakePackageInfo_0(this, Invocation.method(#getPackageInfo, [])),
            ),
          )
          as _i5.Future<_i2.PackageInfo>);
}
